name: ETL Supabase desde delitosmexico.onc.org.mx

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"  # Ejecutar todos los días a las 12:00 UTC (6:00am CDMX)

jobs:
  run-etl:
    runs-on: ubuntu-latest

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

    steps:
      - name: 🧾 Clonar repositorio
        uses: actions/checkout@v3

      - name: 🐍 Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 📦 Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests supabase

      - name: 🚀 Ejecutar script de actualización
        run: python actualizar_delitos.py
